### 1 Read csv file

### 
- 指定 列 dtype

In [ ]:
import pandas as pd
df_projects = pd.read_csv("projects_data.csv",dtype={'financier':str})
# or

df_projects = pd.read_csv("projects_data.csv",dtype=str)

- 打印各列 空值数

In [ ]:
df_projects.isnull().sum()

- 打印各行 空值数

In [ ]:
df_population.isnull().sum(axis=1)

- skiprows

In [ ]:
df_population = pd.read_csv("population_data.csv",skiprows=4)

- 删除特定 列

In [ ]:
df_population = df_population.drop("Unnamed: 62",axis=1)

- 打印 有空值 行

In [ ]:
df_population[df_population.isnull().any(axis=1)]

### 2 读取 JSON 和 XML

###  JSON formatted in different ways:

- 'split' : dict like {index -> [index], columns -> [columns], data -> [values]}

- 'records' : list like [{column -> value}, ... , {column -> value}]

- 'index' : dict like {index -> {column -> value}}

- 'columns' : dict like {column -> {index -> value}}

- 'values' : just the values array

In [ ]:
df_json = pd.read_json("population_data.json",orient="records")

- Other Ways to Read in JSON

In [ ]:
import json

# read in the JSON file
with open('population_data.json') as f:
    json_data = json.load(f)

# print the first record in the JSON file
print(json_data[0])
print('\n')

# show that JSON data is essentially a dictionary
print(json_data[0]['Country Name'])
print(json_data[0]['Country Code'])

### 3 读取 XML

In [ ]:
from bs4 import BeautifulSoup

with open("population_data.xml") as fp:
    soup = BeautifulSoup(fp, "lxml") # lxml is the Parser type

In [ ]:
# output the first 5 records in the xml file
# this is an example of how to navigate the XML document with BeautifulSoup
i = 0
# use the find_all method to get all record tags in the document
for record in soup.find_all("record"):
    i += 1
    for record in record.find_all("field"):
        print( record['name'],":", record.text)
    print()
    if i == 5:
        break

In [ ]:
# TODO: Create a pandas data frame from the XML data.
# HINT: You can use dictionaries to create pandas data frames.
# HINT: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.from_dict.html#pandas.DataFrame.from_dict
# HINT: You can make a dictionary for each column or for each row (See the link above for more information)
# HINT: Modify the code from the previous code cell
Dict ={}
# use the find_all method to get all record tags in the document
for record in soup.find_all('record'):
    # use the find_all method to get all fields in each record
    for record in record.find_all('field'):
        if record['name'] in Dict:
            Dict[record['name']].append(record.text)
        else:
            Dict[record["name"]]=[record.text]
df = pd.DataFrame.from_dict(Dict)
df.head()

### Extract Data from SQL Databases

- Demo: SQLite3 and Pandas

In [ ]:
import sqlite3
import pandas as pd

# connect to the database
conn = sqlite3.connect("population_data.db")

# run a query
pd.read_sql("SELECT * FROM population_data",conn)

In [ ]:
pd.read_sql('SELECT "Country_Name", "Country_Code", "1960" FROM population_data',conn)

- Demo: SQLAlchemy and Pandas
- If you are working with a different type of database such as MySQL or PostgreSQL, you can use the SQLAlchemy library with pandas. Here are the instructions for connecting to different types of databases using SQLAlchemy.

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
## 
# create a database engine 
# to find the correct file path, use the python os library:
# import os
# print(os.getcwd())
#
###

engine = create_engine('sqlite:////home/workspace/3_sql_exercise/population_data.db')
pd.read_sql("SELECT * FROM population_data", engine)

### Example Indicators API

In [1]:
import requests 
import pandas as pd
url = 'http://api.worldbank.org/v2/countries/br;cn;us;de/indicators/SP.POP.TOTL/?format=json&per_page=1000'
r = requests.get(url)
r.json()

[{'lastupdated': '2018-09-21',
  'page': 1,
  'pages': 1,
  'per_page': 1000,
  'total': 232},
 [{'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2017',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 209288278},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2016',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 207652865},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2015',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 205962108},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2014',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 204213133},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2013',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 202408632},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2012',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 200560983},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2011',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 198686688},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2010',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 196796269},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2009',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 194895996},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2008',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 192979029},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2007',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 191026637},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2006',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 189012412},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2005',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 186917361},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2004',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 184738458},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2003',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 182482149},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2002',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 180151021},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2001',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 177750670},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '2000',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 175287587},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1999',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 172759243},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1998',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 170170640},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1997',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 167545164},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1996',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 164913306},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1995',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 162296612},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1994',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 159705123},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1993',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 157132682},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1992',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 154564278},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1991',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 151976577},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1990',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 149352145},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1989',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 146691981},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1988',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 144001542},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1987',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 141273488},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1986',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 138499464},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1985',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 135676281},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1984',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 132800684},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1983',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 129882321},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1982',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 126947365},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1981',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 124030908},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1980',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 121159761},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1979',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 118342626},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1978',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 115577669},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1977',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 112867867},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1976',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 110213082},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1975',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 107612100},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1974',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 105069367},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1973',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 102584278},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1972',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 100143598},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1971',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 97728961},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1970',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 95326793},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1969',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 92935072},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1968',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 90557064},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1967',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 88191378},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1966',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 85837799},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1965',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 83498020},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1964',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 81168654},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1963',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 78854019},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1962',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 76573248},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1961',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 74351763},
  {'country': {'id': 'BR', 'value': 'Brazil'},
   'countryiso3code': 'BRA',
   'date': '1960',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 72207554},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2017',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1386395000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2016',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1378665000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2015',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1371220000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2014',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1364270000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2013',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1357380000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2012',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1350695000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2011',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1344130000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2010',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1337705000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2009',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1331260000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2008',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1324655000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2007',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1317885000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2006',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1311020000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2005',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1303720000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2004',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1296075000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2003',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1288400000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2002',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1280400000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2001',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1271850000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '2000',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1262645000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '1999',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1252735000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '1998',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1241935000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '1997',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1230075000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '1996',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1217550000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '1995',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1204855000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '1994',
   'decimal': 0,
   'indicator': {'id': 'SP.POP.TOTL', 'value': 'Population, total'},
   'obs_status': '',
   'unit': '',
   'value': 1191835000},
  {'country': {'id': 'CN', 'value': 'China'},
   'countryiso3code': 'CHN',
   'date': '1993',
   'decimal': 0,

In [3]:
pd.DataFrame(r.json()[1]).head()

,country,countryiso3code,date,decimal,indicator,obs_status,unit,value
0,"{'id': 'BR', 'value': 'Brazil'}",BRA,2017,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,209288278
1,"{'id': 'BR', 'value': 'Brazil'}",BRA,2016,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,207652865
2,"{'id': 'BR', 'value': 'Brazil'}",BRA,2015,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,205962108
3,"{'id': 'BR', 'value': 'Brazil'}",BRA,2014,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,204213133
4,"{'id': 'BR', 'value': 'Brazil'}",BRA,2013,0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...",,,202408632

In [5]:
# TODO: get the url ready
url = 'http://api.worldbank.org/v2/countries/ch/indicators/SP.RUR.TOTL/?format=json&date=1995:2001'

# TODO: send the request
r = requests.get(url)

# TODO: output the json using the json method like in the previous example
pd.DataFrame(r.json()[1]).head()

,country,countryiso3code,date,decimal,indicator,obs_status,unit,value
0,"{'id': 'CH', 'value': 'Switzerland'}",CHE,2001,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1924949
1,"{'id': 'CH', 'value': 'Switzerland'}",CHE,2000,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1912232
2,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1999,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1897587
3,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1998,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1884719
4,"{'id': 'CH', 'value': 'Switzerland'}",CHE,1997,0,"{'id': 'SP.RUR.TOTL', 'value': 'Rural populati...",,,1875299